"""
Django settings for ecomstore project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SSL_ON = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!00o(%yd773+2_&3metr@1v#3+wn7s&k+9z9_g_u5ljn5-+(zy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'preview',
    'catalog',
    'utils',
    'cart',
    'checkout',
    'mpesa_api',
    'accounts',
    'django.contrib.flatpages',
    'django.contrib.sites',
]

SITE_ID = 1

MIDDLEWARE = [
    'utils.SSLMiddleware.SSLRedirectMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

ROOT_URLCONF = 'ecomstore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'utils.context_processors.ecomstore',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecomstore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ezi$ecomstore',
        'USER': 'ezi',
        'PASSWORD': 'ecomstore',
        'HOST': 'ezi.mysql.pythonanywhere-services.com',
        'PORT': '3306',
        'OPTIONS': {
            # "init_command": "SET foreign_key_checks = 0;",
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation'
                '.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
LOGIN_URL = '/myaccounts/login/'

LOGIN_REDIRECT_URL = '/myaccounts/my_account/'

LOGIN_REDIRECT_URL = '/'

AUTH_PROFILE_MODULE = 'accounts.userprofile'

SECURE_SSL_REDIRECT = True

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticFILES')


# Media settings
MEDIA_URL = '/static/media/'


# Site template settings
SITE_NAME = 'EZINET MALL'

META_KEYWORDS = 'Food staff, Clothes, Electronics and so  much  more. '

META_DESCRIPTION = 'Ezinet mall is an online supplier of all your  shopping  needs' \
                   ' '

# AUTHORIZE.NET SETTINGS
AUTHNET_POST_URL = 'https://apitest.authorize.net/xml/v1/request.api'
AUTHNET_LOGIN = '7N9gfrXQ4m6b'
AUTHNET_KEY = '5837S744yzgEvV4J'
AUTHNET_TTYPE = 'authCaptureTransaction'
USD_RATE = 100

# MPESA SETTINGS
CONSUMER_KEY = '6VI5N8UfjQsbxnGf8GoJGvYidll2d8Wa'
CONSUMER_SECRET = 'iJRGwnYRDQh9j6uw'
OAUTH_API = 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials'
PAYBILL_NO = "174379"
c2bpaybill = 600582
pass_key = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_URL = 'sandbox.safaricom.co.ke'
stkpush_uri = '/mpesa/stkpush/v1/processrequest'
REGISTER_URI = '/mpesa/c2b/v1/registerurl'
QUERYSTK = '/mpesa/stkpushquery/v1/query'
C2B_URI = '/mpesa/c2b/v1/simulate'
