# Generated by Django 2.1.7 on 2020-06-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200621_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingmpesa',
            name='cart',
            field=models.TextField(),
        ),
    ]
